version: '3.8'

services:
  postgres:
    image: postgres:16-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  server:
    build:
      dockerfile: Dockerfile.prod
      context: ./server
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks_db
    ports:
      - '3000:3000'

  client_build:
    build:
      dockerfile: Dockerfile.prod
      context: ./client
    volumes:
      - ./client/dist:/app/dist
  client_server:
    image: nginx:1.25.4-alpine
    ports:
      - '80:80'
    volumes:
      - ./client/dist:/usr/share/nginx/html

volumes:
  pg_data:
      