version: '3.8'

services:
  postgres:
    image: postgres:16-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: './server'
    depends_on:
      - postgres
    volumes:
      - /server/node_modules
      - ./server:/api
    ports:
      - '3001:3000'

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - server
    volumes:
      - /client/node_modules
      - ./client:/app
    ports:
      - "5173:5173"

volumes:
  pg_data: