FROM node:20.11.1-alpine3.18

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm ci

COPY ./ ./

RUN npx prisma generate

RUN npm run build

# CMD ["npm", "run", "build"]
CMD ["node", "dist/main"]